---
title: "Importing and Cleaning Data"
output: html_document
date: "2023-11-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(stringr)

here()
```

Wake County
```{r}
#reading in data for daily maximum temperatures from May to September 1979 to 2021 in Wake County
WakeCo_DailyMaxTemp <- 
  read.csv(here("Raw/CDC_WakeCo_DailyMaxTemp_79-21.csv"))

#making the Report.Date column into date format
WakeCo_DailyMaxTemp$Report.Date <- as.Date(WakeCo_DailyMaxTemp$Report.Date)

#getting rid of columns not needed
WakeCo_DailyMaxTemp <- WakeCo_DailyMaxTemp %>% 
  select(State, County, Report.Date, Year, Value)

#renaming value column for clarity
WakeCo_DailyMaxTemp <- WakeCo_DailyMaxTemp %>%
  rename("Daily.Max.Temp" = "Value")

#separating date column so month and data are separate
WakeCo_DailyMaxTemp[c("yr", "Month", "Day")] <- 
  str_split_fixed(WakeCo_DailyMaxTemp$Report.Date, "-", 3)

#getting rid of extra year column, day column, and report date column
WakeCo_DailyMaxTemp <- WakeCo_DailyMaxTemp %>% 
  select(State, County, Month, Year, Daily.Max.Temp)

#Renaming month columns to have names instead of numbers
WakeCo_DailyMaxTemp$Month <- str_replace_all(WakeCo_DailyMaxTemp$Month, 
                                             "05", "May")
WakeCo_DailyMaxTemp$Month <- str_replace_all(WakeCo_DailyMaxTemp$Month, 
                                             "06", "June")
WakeCo_DailyMaxTemp$Month <- str_replace_all(WakeCo_DailyMaxTemp$Month, 
                                             "07", "July")
WakeCo_DailyMaxTemp$Month <- str_replace_all(WakeCo_DailyMaxTemp$Month, 
                                             "08", "August")
WakeCo_DailyMaxTemp$Month <- str_replace_all(WakeCo_DailyMaxTemp$Month, 
                                             "09", "September")

#combine month and date into same column
WakeCo_DailyMaxTemp <- WakeCo_DailyMaxTemp %>%
  unite(col = "Date", c("Month", "Year"), sep = " ")

#find average daily temp for each month
WakeCo_DailyMaxTemp <- WakeCo_DailyMaxTemp %>% 
  group_by(Date) %>%
  mutate(Avg_Monthly_Temp = mean(Daily.Max.Temp))

#removing daily max temp column
WakeCo_DailyMaxTemp <- WakeCo_DailyMaxTemp %>% 
  select(State, County, Date, Avg_Monthly_Temp)

#keeping only one column from each month
WakeCo_DailyMaxTemp <- unique(WakeCo_DailyMaxTemp)

WakeCo_DailyMaxTemp
```

Orange County
```{r}
#reading in data for daily maximum temperatures from May to September 1979 to 2021 in Orange County
OrangeCo_DailyMaxTemp <- 
  read.csv(here("Raw/CDC_OrangeCo_DailyMaxTemp_79-21.csv"))

#making the Report.Date column into date format
OrangeCo_DailyMaxTemp$Report.Date <- as.Date(OrangeCo_DailyMaxTemp$Report.Date)

#getting rid of columns not needed
OrangeCo_DailyMaxTemp <- OrangeCo_DailyMaxTemp %>% 
  select(State, County, Report.Date, Year, Value)

#renaming value column for clarity
OrangeCo_DailyMaxTemp <- OrangeCo_DailyMaxTemp %>%
  rename("Daily.Max.Temp" = "Value")

#separating date column so month and data are separate
OrangeCo_DailyMaxTemp[c("yr", "Month", "Day")] <- 
  str_split_fixed(OrangeCo_DailyMaxTemp$Report.Date, "-", 3)

#getting rid of extra year column, day column, and report date column
OrangeCo_DailyMaxTemp <- OrangeCo_DailyMaxTemp %>% 
  select(State, County, Month, Year, Daily.Max.Temp)

#Renaming month columns to have names instead of numbers
OrangeCo_DailyMaxTemp$Month <- str_replace_all(OrangeCo_DailyMaxTemp$Month, 
                                             "05", "May")
OrangeCo_DailyMaxTemp$Month <- str_replace_all(OrangeCo_DailyMaxTemp$Month, 
                                             "06", "June")
OrangeCo_DailyMaxTemp$Month <- str_replace_all(OrangeCo_DailyMaxTemp$Month, 
                                             "07", "July")
OrangeCo_DailyMaxTemp$Month <- str_replace_all(OrangeCo_DailyMaxTemp$Month, 
                                             "08", "August")
OrangeCo_DailyMaxTemp$Month <- str_replace_all(OrangeCo_DailyMaxTemp$Month, 
                                             "09", "September")

#combine month and date into same column
OrangeCo_DailyMaxTemp <- OrangeCo_DailyMaxTemp %>%
  unite(col = "Date", c("Month", "Year"), sep = " ")

#find average daily temp for each month
OrangeCo_DailyMaxTemp <- OrangeCo_DailyMaxTemp %>% 
  group_by(Date) %>%
  mutate(Avg_Monthly_Temp = mean(Daily.Max.Temp))

#removing daily max temp column
OrangeCo_DailyMaxTemp <- OrangeCo_DailyMaxTemp %>% 
  select(State, County, Date, Avg_Monthly_Temp)

#keeping only one column from each month
OrangeCo_DailyMaxTemp <- unique(OrangeCo_DailyMaxTemp)

OrangeCo_DailyMaxTemp
```

Durham County
```{r}

#reading in data for daily maximum temperatures from May to September 1979 to 2021 in Durham County
DurhamCo_DailyMaxTemp <- 
  read.csv(here("Raw/CDC_DurhamCo_DailyMaxTemp_79-21.csv"))

#making the Report.Date column into date format
DurhamCo_DailyMaxTemp$Report.Date <- as.Date(DurhamCo_DailyMaxTemp$Report.Date)

#getting rid of columns not needed
DurhamCo_DailyMaxTemp <- DurhamCo_DailyMaxTemp %>% 
  select(State, County, Report.Date, Year, Value)

#renaming value column for clarity
DurhamCo_DailyMaxTemp <- DurhamCo_DailyMaxTemp %>%
  rename("Daily.Max.Temp" = "Value")

#separating date column so month and data are separate
DurhamCo_DailyMaxTemp[c("yr", "Month", "Day")] <- 
  str_split_fixed(DurhamCo_DailyMaxTemp$Report.Date, "-", 3)

#getting rid of extra year column, day column, and report date column
DurhamCo_DailyMaxTemp <- DurhamCo_DailyMaxTemp %>% 
  select(State, County, Month, Year, Daily.Max.Temp)

#Renaming month columns to have names instead of numbers
DurhamCo_DailyMaxTemp$Month <- str_replace_all(DurhamCo_DailyMaxTemp$Month, 
                                             "05", "May")
DurhamCo_DailyMaxTemp$Month <- str_replace_all(DurhamCo_DailyMaxTemp$Month, 
                                             "06", "June")
DurhamCo_DailyMaxTemp$Month <- str_replace_all(DurhamCo_DailyMaxTemp$Month, 
                                             "07", "July")
DurhamCo_DailyMaxTemp$Month <- str_replace_all(DurhamCo_DailyMaxTemp$Month, 
                                             "08", "August")
DurhamCo_DailyMaxTemp$Month <- str_replace_all(DurhamCo_DailyMaxTemp$Month, 
                                             "09", "September")

#combine month and date into same column
DurhamCo_DailyMaxTemp <- DurhamCo_DailyMaxTemp %>%
  unite(col = "Date", c("Month", "Year"), sep = " ")

#find average daily temp for each month
DurhamCo_DailyMaxTemp <- DurhamCo_DailyMaxTemp %>% 
  group_by(Date) %>%
  mutate(Avg_Monthly_Temp = mean(Daily.Max.Temp))

#removing daily max temp column
DurhamCo_DailyMaxTemp <- DurhamCo_DailyMaxTemp %>% 
  select(State, County, Date, Avg_Monthly_Temp)

#keeping only one column from each month
DurhamCo_DailyMaxTemp <- unique(DurhamCo_DailyMaxTemp)

DurhamCo_DailyMaxTemp
```

Triangle
```{r}
#combine data for all three counties into a data frame that encompasses the whole triangle
Triangle_DailyMaxTemp <- left_join(DurhamCo_DailyMaxTemp, WakeCo_DailyMaxTemp, 
          by = c("Date", "State", "County", "Avg_Monthly_Temp"))

Triangle_DailyMaxTemp <- left_join(OrangeCo_DailyMaxTemp, Triangle_DailyMaxTemp,
          by = c("Date", "State", "County", "Avg_Monthly_Temp"))

Triangle_DailyMaxTemp
```

Extreme Heat Days NC all counties
```{r}
#data for number of extreme heat days (above 90 F) from May to September in all NC counties from 1979-2021
NC_ExHeatDays <- 
  read.csv(here("Raw/CDC_NC_ExtremeHeatDays_79-21.csv"), stringsAsFactors=T)

#remove unnecessary columns
NC_ExHeatDays <- NC_ExHeatDays %>% select(Census.Tract, Year, Value)

#remove unnecessary text from county column
NC_ExHeatDays$Census.Tract <- word(NC_ExHeatDays$Census.Tract, 1)

#renaming columns for clarity
NC_ExHeatDays <- NC_ExHeatDays %>%
  rename("County" = "Census.Tract", "Count_ExHeat_Days" = "Value")

#removing years not needed
NC_ExHeatDays <- NC_ExHeatDays[!(NC_ExHeatDays$Year == "1979" | 
    NC_ExHeatDays$Year == "1980" | NC_ExHeatDays$Year == "1981" | 
      NC_ExHeatDays$Year == "1982" | NC_ExHeatDays$Year == "1983" | 
      NC_ExHeatDays$Year == "1984" | NC_ExHeatDays$Year == "1985" | 
      NC_ExHeatDays$Year == "1986" | NC_ExHeatDays$Year == "1987" | 
      NC_ExHeatDays$Year == "1988" | NC_ExHeatDays$Year == "1989" | 
      NC_ExHeatDays$Year == "1990" | NC_ExHeatDays$Year == "1991" | 
      NC_ExHeatDays$Year == "1992" | NC_ExHeatDays$Year == "1993" | 
      NC_ExHeatDays$Year == "1994" | NC_ExHeatDays$Year == "1995" | 
      NC_ExHeatDays$Year == "1996" | NC_ExHeatDays$Year == "1997" | 
      NC_ExHeatDays$Year == "1998" | NC_ExHeatDays$Year == "1999" | 
      NC_ExHeatDays$Year == "2000" | NC_ExHeatDays$Year == "2001" | 
      NC_ExHeatDays$Year == "2002" | NC_ExHeatDays$Year == "2003" |
      NC_ExHeatDays$Year == "2004" | NC_ExHeatDays$Year == "2005" | 
      NC_ExHeatDays$Year == "2006" | NC_ExHeatDays$Year == "2007"),]


NC_ExHeatDays
```

Heat Hospitalizations 
```{r}
#read in crude rate of ED visits for HRI per 100,000 people for all states from 2008-2021
NC_HeatED <- 
  read.csv(here("Raw/CDC_EDvisits_bystate_08-21.csv"), stringsAsFactors=T)

#remove unnecessary columns
NC_HeatED <- NC_HeatED %>%
  select(State, Year, Value)

#pull only NC data
NC_HeatED <- NC_HeatED %>%
  subset(State == "North Carolina")

#rename columns for clarity
NC_HeatED <- NC_HeatED %>%
  rename("ED.Visits.per.100000" = "Value")
  


NC_HeatED
```

AQI 2008
```{r}
#read in AQI data from 2008 from all US counties 
AQI_2008 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2008.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2008 <- AQI_2008 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2008 <- AQI_2008 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2008
```

AQI 2009
```{r}
#read in AQI data from 2009 from all US counties 
AQI_2009 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2009.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2009 <- AQI_2009 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2009 <- AQI_2009 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2009
```

AQI 2010
```{r}
#read in AQI data from 2010 from all US counties 
AQI_2010 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2010.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2010 <- AQI_2010 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2010 <- AQI_2010 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2010
```

AQI 2011
```{r}
#read in AQI data from 2011 from all US counties 
AQI_2011 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2011.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2011 <- AQI_2011 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2011 <- AQI_2011 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2011
```

AQI 2012
```{r}
#read in AQI data from 2012 from all US counties 
AQI_2012 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2012.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2012 <- AQI_2012 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2012 <- AQI_2012 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2012
```

AQI 2013
```{r}
#read in AQI data from 2013 from all US counties 
AQI_2013 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2013.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2013 <- AQI_2013 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2013 <- AQI_2013 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2013
```

AQI 2014
```{r}
#read in AQI data from 2014 from all US counties 
AQI_2014 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2014.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2014 <- AQI_2014 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2014 <- AQI_2014 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2014
```

AQI 2015
```{r}
#read in AQI data from 2015 from all US counties 
AQI_2015 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2015.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2015 <- AQI_2015 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2015 <- AQI_2015 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2015
```

AQI 2016
```{r}
#read in AQI data from 2016 from all US counties 
AQI_2016 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2016.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2016 <- AQI_2016 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2016 <- AQI_2016 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2016
```

AQI 2017
```{r}
#read in AQI data from 2017 from all US counties 
AQI_2017 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2017.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2017 <- AQI_2017 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2017 <- AQI_2017 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2017
```

AQI 2018
```{r}
#read in AQI data from 2018 from all US counties 
AQI_2018 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2018.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2018 <- AQI_2018 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2018 <- AQI_2018 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2018
```

AQI 2019
```{r}
#read in AQI data from 2019 from all US counties 
AQI_2019 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2019.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2019 <- AQI_2019 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2019 <- AQI_2019 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2019
```

AQI 2020
```{r}
#read in AQI data from 2010 from all US counties 
AQI_2020 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2020.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2020 <- AQI_2020 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2020 <- AQI_2020 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2020
```

AQI 2021
```{r}
#read in AQI data from 2021 from all US counties 
AQI_2021 <- read.csv(here("Raw/EPA_dailyAQI_USAbyCo_2021.csv"), 
                     stringsAsFactors = TRUE)

#include data only from NC
AQI_2021 <- AQI_2021 %>%
  subset(State == "North Carolina")

#remove unnecessary columns
AQI_2021 <- AQI_2021 %>%
  select(County, Year, Days.with.AQI, Median.AQI, Max.AQI, Good.Days, 
         Moderate.Days, Unhealthy.for.Sensitive.Groups.Days, Unhealthy.Days, 
         Very.Unhealthy.Days, Hazardous.Days)

AQI_2021
```

Join 2008-2021 AQI data
```{r}
df1 <- full_join(AQI_2009, AQI_2008)

df2 <- full_join(AQI_2010, df1)
          
df3 <- full_join(AQI_2011, df2)  

df4 <- full_join(AQI_2012, df3)  

df5 <- full_join(AQI_2013, df4)   

df6 <- full_join(AQI_2014, df5)   

df7 <- full_join(AQI_2015, df6)   

df8 <- full_join(AQI_2016, df7)   

df9 <- full_join(AQI_2017, df8) 

df10 <- full_join(AQI_2018, df9) 

df11 <- full_join(AQI_2019, df10) 

df12 <- full_join(AQI_2020, df11) 

NC_AQI <- full_join(AQI_2021, df12) 


NC_AQI
```


Exporting
```{r}
#exporting cleaned data frames
write.csv(Triangle_DailyMaxTemp, "Triangle_DailyMaxTemp_Clean.csv", 
          row.names=TRUE)

write.csv(WakeCo_DailyMaxTemp, "WakeCo_DailyMaxTemp_Clean.csv", 
          row.names=TRUE)

write.csv(OrangeCo_DailyMaxTemp, "OrangeCo_DailyMaxTemp_Clean.csv", 
          row.names=TRUE)

write.csv(DurhamCo_DailyMaxTemp, "DurhamCo_DailyMaxTemp_Clean.csv", 
          row.names=TRUE)

write.csv(NC_HeatED, "CDC_EDvisits_NC_08-21_Clean.csv", 
          row.names=TRUE)

write.csv(NC_ExHeatDays, "CDC_ExHeatDays_NCbyCo_08-21_Clean.csv", 
          row.names=TRUE)

write.csv(NC_AQI, "EPA_dailyAQI_NCbyCo_08-21_Clean.csv", 
          row.names=TRUE)

```

