---
title: "Regressions"
output: html_document
date: "2023-11-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#pull AQI data by year for NC not by county
NC_AQI_byyear <- NC_AQI %>% select(Year, Annual.AQI.Mean)
NC_AQI_byyear <- unique(NC_AQI_byyear)
NC_AQI_byyear

#pull extreme heat data by year for NC not by county
NC_ExHeatDays_byyear <- NC_ExHeatDays %>% select(Year, NC_Annual_Agv_ExHeatDays)
NC_ExHeatDays_byyear <- unique(NC_ExHeatDays_byyear)
NC_ExHeatDays_byyear

NC_ExHeatDays_byyear
NC_AQI_byyear
NC_HeatED 

test <- inner_join(NC_ExHeatDays_byyear, NC_AQI_byyear)

heat_health_data <- inner_join(test, NC_HeatED )

heat_health_data

```

```{r}
lm(ED.Visits.per.100000 ~ Annual.AQI.Mean, data = heat_health_data)




ggplot(data = heat_health_data, 
       aes(x = NC_Annual_Agv_ExHeatDays, y = Annual.AQI.Mean)) +
  geom_point() +
  theme_minimal() +



ggplot(data = heat_health_data, 
       aes(x = Year, y = ED.Visits.per.100000)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Year", y = "Crude Rate of ED visits per 100,000 people", 
       title = "Heat Related Emergency Department Visits", 
       subtitle = "From 2008-2021 in NC")


ggplot(data = heat_health_data, 
       aes(x = Year, y = NC_Annual_Agv_ExHeatDays)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Year", y = "Number of Extreme Heat Days", 
       title = "Average Number of Annual Extreme Heat Days", 
       subtitle = "From 2008-2021 in NC")


ggplot(data = heat_health_data, 
       aes(x = Year, y = Annual.AQI.Mean)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Year", y = "AQI", 
       title = "Average Annual AQI", subtitle = "From 2008-2021 in NC")


```





